# Informaci칩n del sitio
title: Juan Lara
author: Juan Lara
description: Data Scientist & Mathematical Researcher
avatar: "/assets/img/avatar.jpg"  # A침ade una foto profesional tuya

# Redes sociales
social-network-links:
  email: "larajuand@outlook.com"
  github: JuanLara18
  linkedin: julara
  youtube: "@juanlara"

# Navegaci칩n principal
navbar-links:
  About: "about"
  Research: "research"
  Blog: "blog"
  Projects: "projects"
  Publications: "publications"
  CV: "cv"

# Configuraci칩n visual
navbar-col: "#FFFFFF"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
